#!/usr/bin/env python3
r"""
Task Executor - Multi-Step Plan Execution Engine

Executes multi-step plans generated by the planner agent:
- Sequential and parallel step execution
- Error handling and retry logic
- Progress tracking
- Result aggregation

Usage:
    from modules.planning.task_executor import TaskExecutor

    executor = TaskExecutor(vault_path)
    result = executor.execute_plan(plan)
"""

import json
import logging
import time
import asyncio
from datetime import datetime
from pathlib import Path
from typing import Any, Optional, Callable
from dataclasses import dataclass, asdict, field
from enum import Enum
from concurrent.futures import ThreadPoolExecutor, as_completed

import dotenv

# Load environment variables
dotenv.load_dotenv()

# Windows-safe logging setup
import logging
class WindowsSafeHandler(logging.StreamHandler):
    """Logging handler that replaces emojis with ASCII on Windows."""
    EMOJI_MAP = {
        '👁️': '[O]', '📋': '[T]', '🤖': '[AI]', '✅': '[OK]', '❌': '[X]',
        '⚠️': '[!]', '📝': '[N]', '🔄': '[~]', '📊': '[D]', '📁': '[F]',
    }
    def emit(self, record):
        try:
            msg = self.format(record)
            if sys.platform == "win32":
                for emoji, repl in self.EMOJI_MAP.items():
                    msg = msg.replace(emoji, repl)
            self.stream.write(msg + self.terminator)
            self.flush()
        except Exception:
            try:
                msg = self.format(record).encode('ascii', 'ignore').decode('ascii')
                self.stream.write(msg + self.terminator)
                self.flush()
            except Exception:
                pass

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
if not logger.handlers:
    handler = WindowsSafeHandler()
    handler.setFormatter(logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s"))
    logger.addHandler(handler)


class StepStatus(Enum):
    """Step execution status."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"
    RETRYING = "retrying"


class ExecutionMode(Enum):
    """Plan execution mode."""
    SEQUENTIAL = "sequential"
    PARALLEL = "parallel"
    HYBRID = "hybrid"


@dataclass
class StepResult:
    """Result of a single step execution."""
    step_id: int
    action: str
    description: str
    status: str
    started_at: str = ""
    completed_at: str = ""
    result: dict = None
    error: str = ""
    retry_count: int = 0

    def __post_init__(self):
        if self.result is None:
            self.result = {}
        if not self.started_at:
            self.started_at = datetime.now().isoformat()

    def to_dict(self) -> dict:
        """Convert to dictionary."""
        return asdict(self)


@dataclass
class ExecutionResult:
    """Result of plan execution."""
    execution_id: str
    plan_id: str
    task_id: str
    status: str
    started_at: str
    completed_at: str = ""
    total_steps: int = 0
    completed_steps: int = 0
    failed_steps: int = 0
    skipped_steps: int = 0
    step_results: list = None
    error: str = ""
    metadata: dict = None

    def __post_init__(self):
        if self.step_results is None:
            self.step_results = []
        if self.metadata is None:
            self.metadata = {}

    def to_dict(self) -> dict:
        """Convert to dictionary."""
        return asdict(self)


class TaskExecutor:
    """
    Task Execution Engine.

    Executes multi-step plans with support for:
    - Sequential and parallel execution
    - Automatic retries
    - Error handling
    - Progress tracking
    """

    def __init__(
        self,
        vault_path: Path = None,
        max_retries: int = 3,
        retry_delay: float = 1.0,
        timeout_per_step: int = 300
    ):
        """
        Initialize task executor.

        Args:
            vault_path: Path to Obsidian vault
            max_retries: Maximum retry attempts per step
            retry_delay: Delay between retries (seconds)
            timeout_per_step: Timeout per step (seconds)
        """
        self.vault_path = vault_path or Path.cwd() / "Vault"
        self.max_retries = max_retries
        self.retry_delay = retry_delay
        self.timeout_per_step = timeout_per_step

        # Folders
        self.in_progress = self.vault_path / "In_Progress"
        self.executor_folder = self.in_progress / "task_executor"
        self.logs_folder = self.vault_path / "Logs"

        # Create folders
        for folder in [self.executor_folder, self.logs_folder]:
            folder.mkdir(parents=True, exist_ok=True)

        # Action handlers registry
        self._handlers: dict[str, Callable] = {}
        self._register_default_handlers()

        # Execution state
        self.current_execution: Optional[ExecutionResult] = None

        logger.info(f"TaskExecutor initialized at {self.vault_path}")

    def _register_default_handlers(self):
        """Register default action handlers."""
        self._handlers = {
            "read_email": self._handle_read_email,
            "read_message": self._handle_read_message,
            "classify_intent": self._handle_classify_intent,
            "classify_lead": self._handle_classify_lead,
            "draft_response": self._handle_draft_response,
            "submit_for_approval": self._handle_submit_approval,
            "create_crm_entry": self._handle_create_crm,
            "generate_proposal": self._handle_generate_proposal,
            "create_invoice": self._handle_create_invoice,
            "send_followup": self._handle_send_followup,
            "generate_content": self._handle_generate_content,
            "schedule_post": self._handle_schedule_post,
            "publish_post": self._handle_publish_post,
            "send_email": self._handle_send_email,
            "send_whatsapp": self._handle_send_whatsapp,
            "fetch_data": self._handle_fetch_data,
            "update_record": self._handle_update_record,
            "create_record": self._handle_create_record,
            "notify": self._handle_notify,
            "wait_approval": self._handle_wait_approval,
        }

    def register_handler(self, action: str, handler: Callable):
        """
        Register a custom action handler.

        Args:
            action: Action name
            handler: Handler function
        """
        self._handlers[action] = handler
        logger.info(f"Registered handler for action: {action}")

    def execute_plan(
        self,
        plan: dict,
        task: dict = None,
        mode: ExecutionMode = ExecutionMode.SEQUENTIAL
    ) -> ExecutionResult:
        """
        Execute a plan.

        Args:
            plan: Plan dictionary with steps
            task: Task dictionary (optional)
            mode: Execution mode

        Returns:
            ExecutionResult
        """
        execution_id = f"EXEC_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        plan_id = plan.get("plan_id", "unknown")
        task_id = plan.get("task_id", task.get("task_id", "unknown") if task else "unknown")

        result = ExecutionResult(
            execution_id=execution_id,
            plan_id=plan_id,
            task_id=task_id,
            status="running",
            started_at=datetime.now().isoformat(),
            total_steps=len(plan.get("steps", []))
        )

        self.current_execution = result
        logger.info(f"Starting execution {execution_id} for plan {plan_id}")

        steps = plan.get("steps", [])
        if not steps:
            result.status = "completed"
            result.completed_at = datetime.now().isoformat()
            logger.info("No steps to execute")
            return result

        try:
            if mode == ExecutionMode.SEQUENTIAL:
                result = self._execute_sequential(steps, task, result)
            elif mode == ExecutionMode.PARALLEL:
                result = self._execute_parallel(steps, task, result)
            else:  # HYBRID
                result = self._execute_hybrid(steps, task, result)

        except Exception as e:
            logger.error(f"Execution failed: {e}")
            result.status = "failed"
            result.error = str(e)

        result.completed_at = datetime.now().isoformat()

        # Save execution log
        self._save_execution_log(result)

        logger.info(f"Execution {execution_id} completed with status: {result.status}")
        return result

    def _execute_sequential(
        self,
        steps: list,
        task: dict,
        result: ExecutionResult
    ) -> ExecutionResult:
        """Execute steps sequentially."""
        for step in steps:
            step_result = self._execute_step(step, task, result)
            result.step_results.append(step_result.to_dict())

            if step_result.status == StepStatus.COMPLETED.value:
                result.completed_steps += 1
            elif step_result.status == StepStatus.FAILED.value:
                result.failed_steps += 1

                # Check if step is critical
                if step.get("critical", True):
                    result.status = "failed"
                    result.error = f"Step {step.get('step', '?')} failed: {step_result.error}"
                    break
                else:
                    # Non-critical step, continue
                    logger.warning(f"Non-critical step failed, continuing...")

            elif step_result.status == StepStatus.SKIPPED.value:
                result.skipped_steps += 1

        # Determine final status
        if result.status != "failed":
            if result.failed_steps == 0:
                result.status = "completed"
            elif result.completed_steps > 0:
                result.status = "partial"
            else:
                result.status = "failed"

        return result

    def _execute_parallel(
        self,
        steps: list,
        task: dict,
        result: ExecutionResult
    ) -> ExecutionResult:
        """Execute steps in parallel where possible."""
        # Group steps by dependencies
        # For simplicity, execute all independent steps in parallel
        with ThreadPoolExecutor(max_workers=5) as executor:
            futures = {
                executor.submit(self._execute_step, step, task, result): step
                for step in steps
            }

            for future in as_completed(futures):
                step = futures[future]
                try:
                    step_result = future.result(timeout=self.timeout_per_step)
                    result.step_results.append(step_result.to_dict())

                    if step_result.status == StepStatus.COMPLETED.value:
                        result.completed_steps += 1
                    elif step_result.status == StepStatus.FAILED.value:
                        result.failed_steps += 1

                except Exception as e:
                    result.failed_steps += 1
                    result.step_results.append(StepResult(
                        step_id=step.get("step", 0),
                        action=step.get("action", "unknown"),
                        description=step.get("description", ""),
                        status=StepStatus.FAILED.value,
                        error=str(e)
                    ).to_dict())

        # Determine final status
        if result.failed_steps == 0:
            result.status = "completed"
        elif result.completed_steps > 0:
            result.status = "partial"
        else:
            result.status = "failed"

        return result

    def _execute_hybrid(
        self,
        steps: list,
        task: dict,
        result: ExecutionResult
    ) -> ExecutionResult:
        """Execute steps with hybrid mode (sequential with parallel groups)."""
        # For now, fall back to sequential
        # Can be enhanced to detect parallel groups based on dependencies
        return self._execute_sequential(steps, task, result)

    def _execute_step(
        self,
        step: dict,
        task: dict,
        execution_result: ExecutionResult
    ) -> StepResult:
        """
        Execute a single step with retry logic.

        Args:
            step: Step definition
            task: Task context
            execution_result: Current execution result

        Returns:
            StepResult
        """
        step_id = step.get("step", 0)
        action = step.get("action", "unknown")
        description = step.get("description", "")

        step_result = StepResult(
            step_id=step_id,
            action=action,
            description=description,
            status=StepStatus.RUNNING.value,
            started_at=datetime.now().isoformat()
        )

        logger.info(f"Executing step {step_id}: {action}")

        # Get handler
        handler = self._handlers.get(action)
        if not handler:
            logger.warning(f"No handler for action: {action}")
            step_result.status = StepStatus.SKIPPED.value
            step_result.error = f"No handler registered for action: {action}"
            step_result.completed_at = datetime.now().isoformat()
            return step_result

        # Execute with retries
        for attempt in range(self.max_retries + 1):
            try:
                step_result.retry_count = attempt

                if attempt > 0:
                    logger.info(f"Retry attempt {attempt} for step {step_id}")
                    step_result.status = StepStatus.RETRYING.value
                    time.sleep(self.retry_delay * attempt)  # Exponential backoff

                # Execute handler
                handler_result = handler(step, task, execution_result)

                step_result.status = StepStatus.COMPLETED.value
                step_result.result = handler_result
                step_result.completed_at = datetime.now().isoformat()

                logger.info(f"Step {step_id} completed successfully")
                break

            except Exception as e:
                logger.error(f"Step {step_id} attempt {attempt + 1} failed: {e}")
                step_result.error = str(e)

                if attempt >= self.max_retries:
                    step_result.status = StepStatus.FAILED.value
                    step_result.completed_at = datetime.now().isoformat()
                    logger.error(f"Step {step_id} failed after {self.max_retries + 1} attempts")

        return step_result

    # =========================================================================
    # Default Action Handlers
    # =========================================================================

    def _handle_read_email(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle read_email action."""
        content = task.get("metadata", {}).get("content", "") if task else ""
        return {"status": "completed", "content_length": len(content)}

    def _handle_read_message(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle read_message action."""
        content = task.get("metadata", {}).get("content", "") if task else ""
        return {"status": "completed", "content_length": len(content)}

    def _handle_classify_intent(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle classify_intent action."""
        content = (task.get("metadata", {}).get("content", "") if task else "").lower()

        intent = "general"
        if any(w in content for w in ["urgent", "asap", "emergency"]):
            intent = "urgent"
        elif any(w in content for w in ["question", "help", "how"]):
            intent = "inquiry"
        elif any(w in content for w in ["complaint", "issue", "problem"]):
            intent = "complaint"

        return {"status": "completed", "intent": intent}

    def _handle_classify_lead(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle classify_lead action."""
        content = (task.get("metadata", {}).get("content", "") if task else "").lower()

        quality = "medium"
        if any(w in content for w in ["budget", "price", "cost", "pay"]):
            quality = "high"

        return {"status": "completed", "lead_quality": quality}

    def _handle_draft_response(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle draft_response action."""
        draft_file = self.executor_folder / f"draft_{execution.task_id}.md"
        draft_file.write_text(f"Draft response for {execution.task_id}")
        return {"status": "completed", "draft_file": str(draft_file)}

    def _handle_submit_approval(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle submit_for_approval action."""
        return {"status": "completed", "submitted": True, "awaiting_approval": True}

    def _handle_create_crm(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle create_crm_entry action."""
        crm_file = self.executor_folder / f"crm_{execution.task_id}.json"
        crm_data = {"task_id": execution.task_id, "created_at": datetime.now().isoformat()}
        crm_file.write_text(json.dumps(crm_data, indent=2))
        return {"status": "completed", "crm_file": str(crm_file)}

    def _handle_generate_proposal(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle generate_proposal action."""
        proposal_file = self.executor_folder / f"proposal_{execution.task_id}.md"
        proposal_file.write_text(f"Proposal for {execution.task_id}")
        return {"status": "completed", "proposal_file": str(proposal_file)}

    def _handle_create_invoice(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle create_invoice action."""
        # Would integrate with Odoo in production
        return {"status": "completed", "invoice_created": True}

    def _handle_send_followup(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle send_followup action."""
        return {"status": "completed", "followup_sent": True}

    def _handle_generate_content(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle generate_content action."""
        return {"status": "completed", "content_generated": True}

    def _handle_schedule_post(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle schedule_post action."""
        return {"status": "completed", "post_scheduled": True}

    def _handle_publish_post(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle publish_post action."""
        return {"status": "completed", "post_published": True}

    def _handle_send_email(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle send_email action."""
        return {"status": "completed", "email_sent": True}

    def _handle_send_whatsapp(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle send_whatsapp action."""
        return {"status": "completed", "whatsapp_sent": True}

    def _handle_fetch_data(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle fetch_data action."""
        return {"status": "completed", "data_fetched": True}

    def _handle_update_record(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle update_record action."""
        return {"status": "completed", "record_updated": True}

    def _handle_create_record(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle create_record action."""
        return {"status": "completed", "record_created": True}

    def _handle_notify(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle notify action."""
        return {"status": "completed", "notification_sent": True}

    def _handle_wait_approval(self, step: dict, task: dict, execution: ExecutionResult) -> dict:
        """Handle wait_approval action."""
        return {"status": "completed", "waiting": True, "requires_human": True}

    def _save_execution_log(self, result: ExecutionResult):
        """Save execution log to file."""
        log_file = self.logs_folder / f"EXECUTION_{result.execution_id}.json"
        log_file.write_text(json.dumps(result.to_dict(), indent=2))

    def get_execution_status(self, execution_id: str) -> Optional[dict]:
        """
        Get status of a specific execution.

        Args:
            execution_id: Execution ID

        Returns:
            Execution result dictionary or None
        """
        log_file = self.logs_folder / f"EXECUTION_{execution_id}.json"
        if log_file.exists():
            return json.loads(log_file.read_text())
        return None

    def get_recent_executions(self, limit: int = 10) -> list:
        """
        Get recent executions.

        Args:
            limit: Number of executions to return

        Returns:
            List of execution result dictionaries
        """
        executions = []
        for log_file in sorted(self.logs_folder.glob("EXECUTION_*.json"), reverse=True)[:limit]:
            try:
                data = json.loads(log_file.read_text())
                executions.append(data)
            except:
                pass
        return executions


# =============================================================================
# Factory Function
# =============================================================================

def create_executor(
    vault_path: Path = None,
    max_retries: int = 3
) -> TaskExecutor:
    """
    Create a task executor.

    Args:
        vault_path: Path to vault
        max_retries: Maximum retry attempts

    Returns:
        TaskExecutor instance
    """
    return TaskExecutor(vault_path, max_retries)


# =============================================================================
# CLI Interface
# =============================================================================

def main():
    """Command-line interface for task executor."""
    import argparse

    parser = argparse.ArgumentParser(description="Task Executor")
    parser.add_argument("--vault", type=str, help="Vault path")
    parser.add_argument("--execute", type=str, help="Execute plan from file")
    parser.add_argument("--status", type=str, help="Get execution status")
    parser.add_argument("--recent", action="store_true", help="Show recent executions")

    args = parser.parse_args()

    print("=" * 70)
    print("Task Executor")
    print("=" * 70)

    try:
        vault_path = Path(args.vault) if args.vault else Path.cwd() / "Vault"
        executor = TaskExecutor(vault_path)

        if args.execute:
            plan_file = Path(args.execute)
            if plan_file.exists():
                plan = json.loads(plan_file.read_text())
                print(f"\n⚡ Executing plan from {plan_file.name}...")
                result = executor.execute_plan(plan)
                print(f"\n{'='*70}")
                print(f"Execution: {result.execution_id}")
                print(f"Status: {result.status}")
                print(f"Steps: {result.completed_steps}/{result.total_steps} completed")
                if result.error:
                    print(f"Error: {result.error}")
            else:
                print(f"Plan file not found: {plan_file}")

        elif args.status:
            status = executor.get_execution_status(args.status)
            if status:
                print(f"\n📊 Execution Status:")
                print(f"   Status: {status['status']}")
                print(f"   Completed Steps: {status['completed_steps']}/{status['total_steps']}")
            else:
                print(f"Execution not found: {args.status}")

        elif args.recent:
            executions = executor.get_recent_executions()
            print(f"\n📋 Recent Executions:")
            for exec_data in executions[:5]:
                print(f"   - {exec_data['execution_id']}: {exec_data['status']} "
                      f"({exec_data['completed_steps']}/{exec_data['total_steps']})")

        else:
            print("\nUsage: python -m modules.planning.task_executor --execute|--status|--recent")

    except Exception as e:
        print(f"\n❌ Error: {e}")


if __name__ == "__main__":
    main()
